### ISSUE TITLE
Stuck on installing hpp2plantuml

### ISSUE THREAD

**Issue by jhflow** [cheoljoo/CGADoxygen#2]
I am stuck on the very 1st step. When I ran *run.sh*, I got the following error:
```
Do install hpp2plantuml
Method-1. run setting_env_user_mode.sh in current directory
Method-2. Install by  yourself  from URL)   https://github.com/thibaultmarin/hpp2plantuml
```

so I did *Method-1*. Then, I got another error:
```
hpp2plantuml
#### Checking < hpp2plantuml > Package ####
#### Install hpp2plantuml package ####
Cloning into 'hpp2plantuml'...
remote: Enumerating objects: 295, done.
remote: Total 295 (delta 0), reused 0 (delta 0), pack-reused 295
Receiving objects: 100% (295/295), 129.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (148/148), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from setuptools import setup, find_packages, Command
ImportError: No module named 'setuptools'
```
To resolve this, I installed setuptools by pip:
```
pip install setuptools --user
```
but got the error above again.

(Actually, I got another error first (*fatal: destination path 'hpp2plantuml' already exists and is not an empty directory.*) It was resolved after I removed ./tmp directory. You had better fix *setting_env_user_mode.sh* to remove *./tmp* before cloning *http2plantuml*)

How can I resolve this dependency issue?

+ IMHO, describing prerequisites at *README.md* (or *INSTALL.md*) is very useful.

**Comment by cheoljoo** [comment]
> FYI, I use python 2.7 now.

Thanks. 

setup-tools and hpp2plantuml needs python3 for installation.
markdown-pp needs python for installation.

According to your request , I removed git download directory before cloning.

I am considering the docker.

**Comment by jhflow** [comment]
Thanks. I did not recognize the section "How to install tools" (since it is in the middle of documentation)
By the way, I resolved an issue regarding hpp2plantuml and markdown-pp by using pip.
It works on the python 2.7 either :)
```
pip install hpp2plantuml MarkdownPP --user
```
