### ISSUE TITLE
Some target-specific paths are used

### ISSUE THREAD

**Issue by jhflow** [cheoljoo/CGADoxygen#3]
I found a target-specific path from the warning log:
```
warning: source /home/cheoljoo/code/common_telltale/GP/Apps/Src/MgrTelltale/CGADOXYGEN/build_doxygen is not a readable file or directory... skipping.
```

They should be removed (if not needed) or replaced to the correct path.

**Comment by cheoljoo** [comment]
Yes. Could you change it in Doxyfile (./CGADoxygen/build_doxygen/)?

**Comment by jhflow** [comment]
I made a pull request for this (#4) :)
